#!/usr/bin/env node
/**
 * Auto-register buyer and assign permissions based on subscription plan.
 * Usage: node register_buyer.js <username> <phone> <plan>
 * Plans: basic10 | standard100 | advanced | premium
 */

const fs = require('fs');
const crypto = require('crypto');

const USERS_FILE = '/home/ec2-user/proxy-token-site/data/users.json';
const PROXY_USERS_FILE = '/home/ec2-user/cloud-proxy/users.json';

const TIERS = {
  basic10: {
    role: 'basic_flow',
    price: 20,
    description: '基础行情流套餐 (10只) — 股票+夜盘实时流',
    permissions: {
      ws: { stocks: true, options: false, overnight: true, crypto: false, news: false, boats: false, test: false },
      rest: { stocks_history: false, options_history: false, options_contracts: false, options_snapshots: false, options_snapshots_expiry: false, crypto_orderbooks: false, admin_token_lookup: false, news_history: false }
    }
  },
  standard100: {
    role: 'standard_flow',
    price: 50,
    description: '标准行情流套餐 (100只) — 股票+夜盘实时流',
    permissions: {
      ws: { stocks: true, options: false, overnight: true, crypto: false, news: false, boats: false, test: false },
      rest: { stocks_history: false, options_history: false, options_contracts: false, options_snapshots: false, options_snapshots_expiry: false, crypto_orderbooks: false, admin_token_lookup: false, news_history: false }
    }
  },
  advanced: {
    role: 'advanced',
    price: 100,
    description: '全功能高级套餐 — 股票+期权实时流 + 历史数据 + 新闻',
    permissions: {
      ws: { stocks: true, options: true, overnight: true, crypto: false, news: true, boats: false, test: false },
      rest: { stocks_history: true, options_history: true, options_contracts: false, options_snapshots: false, options_snapshots_expiry: false, crypto_orderbooks: false, admin_token_lookup: false, news_history: true }
    }
  },
  premium: {
    role: 'premium',
    price: 130,
    description: '全包尊享套餐 — 全部实时流 + 全部历史数据',
    permissions: {
      ws: { stocks: true, options: true, overnight: true, crypto: true, news: true, boats: true, test: true },
      rest: { stocks_history: true, options_history: true, options_contracts: true, options_snapshots: true, options_snapshots_expiry: true, crypto_orderbooks: true, admin_token_lookup: false, news_history: true }
    }
  }
};

function readJSON(path, fallback = []) {
  try { return JSON.parse(fs.readFileSync(path, 'utf8')); }
  catch { return fallback; }
}

function writeJSON(path, data) {
  fs.writeFileSync(path, JSON.stringify(data, null, 2));
}

function addUser(username, phone, planKey) {
  const tier = TIERS[planKey];
  if (!tier) {
    console.error(`Unknown plan: ${planKey}. Available: ${Object.keys(TIERS).join(', ')}`);
    process.exit(1);
  }

  // 1. Add to token-site users.json
  const users = readJSON(USERS_FILE);
  const filtered = users.filter(u => u.username !== username);
  filtered.push({
    username,
    phone,
    role: tier.role,
    plan: planKey,
    permissions: tier.permissions
  });
  writeJSON(USERS_FILE, filtered);
  console.log(`[OK] ${username} added to token-site users.json (${tier.description})`);

  // 2. Check proxy registry — do NOT auto-generate token here
  // Token is generated by user via /api/generate-token when they are ready
  let ec2Data = readJSON(PROXY_USERS_FILE, { users: [] });
  if (!ec2Data.users) ec2Data.users = [];

  const existing = ec2Data.users.find(u => u.user_id === username);
  if (existing) {
    console.log(`[INFO] Proxy token already exists for ${username}: ${existing.token} (expires ${existing.expires_at})`);
    console.log(`[INFO] User can regenerate at http://35.88.155.223:3000/ — token will remain the same`);
  } else {
    console.log(`[INFO] No proxy token yet for ${username}`);
    console.log(`[INFO] User generates token at: http://35.88.155.223:3000/ (输入用户名+手机号)`);
    console.log(`[INFO] Expire date starts from that moment + 30 days`);
  }

  return { username, phone, plan: planKey, role: tier.role };
}

// CLI
const [,, username, phone, plan] = process.argv;
if (!username || !phone || !plan) {
  console.log('Usage: node register_buyer.js <username> <phone> <plan>');
  console.log('Plans: basic10 | standard100 | advanced | premium');
  process.exit(1);
}

addUser(username, phone, plan);
